### ISSUE TITLE
Support libgphoto

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/visiond#10]
@fnoop Throwing this out there as an idea for comments. For maverick do we want visiond to be the one stop shop for all camera interfaces? E.g. when we start looking at supporting automated DSLR cameras or other machine vision cameras (point grey, ximea, etc) do you envision visiond doing this or a separate service?

**Comment by fnoop** [comment]
No absolutely not - visiond is purely for streaming live video.  DSLR/imaging etc will be completely separate.

**Comment by SamuelDudley** [comment]
Thanks!
