### ISSUE TITLE
Add uuid to identify visiond for clients

### ISSUE THREAD

**Issue by fnoop** [goodrobots/visiond#26]

**Comment by fnoop** [comment]
Need a repeatable uuid, but one that is unique.  Does not have to be secure.
https://docs.python.org/3.7/library/uuid.html

Try with uuid5, with uuid.NAMESPACE_URL, and pass the webrtc or rtsp URL as the name param. 
 Should be repeatable, and unique across any network.
_rtspurl = f"rtsp://{socket.getfqdn()}:{self.config.args.output_port}/video"
_wsEndpoint = f"wss://{socket.getfqdn()}:6796"

@SamuelDudley - might be an idea to use a similar system for -api instead of uuid4, which I'm not sure is repeatable?

Ideally it needs to be repeatable, as we use the uuid as the key in -web for api and videostream definitions.

**Comment by SamuelDudley** [comment]
Yep, good idea. I looked at this for -api and was planning to make the change.

edit: You are also correct in stating that uuid4 is not repeatable
