### ISSUE TITLE
zeroconf not broadcasting 

### ISSUE THREAD

**Issue by fnoop** [goodrobots/visiond#28]
webrtc service has to be restarted for visiond to pick up janus and broadcast zeroconf.

Also an error:
```
Apr 16 17:19:59 maverick-raspberrylite python3[686]: 2020-04-16 17:19:59,124 - zeroconf - WARNING - Exception occurred:
Apr 16 17:19:59 maverick-raspberrylite python3[686]: Traceback (most recent call last):
Apr 16 17:19:59 maverick-raspberrylite python3[686]:   File "/srv/maverick/software/python/lib/python3.7/site-packages/zeroconf/__init__.py", line 2638, in send
Apr 16 17:19:59 maverick-raspberrylite python3[686]:     bytes_sent = s.sendto(packet, 0, (real_addr, port))
Apr 16 17:19:59 maverick-raspberrylite python3[686]: OSError: [Errno 101] Network is unreachable
```

**Comment by SamuelDudley** [comment]
Does the service wait for network to be ready?

**Comment by SamuelDudley** [comment]
Yes it does... Hmmm

**Comment by fnoop** [comment]
Yes, problem fixed in https://github.com/goodrobots/maverick/issues/945.
The additional 'Network is unreachable' is because zeroconf tries to broadcast out on a downed interface (eth0 in this case, which has nothing plugged in).  However the error is trapped and the thread continues, so can be safely ignored.
